### ISSUE TITLE
Program falls over when logging in...

### ISSUE THREAD

**Issue by steverob1066** [1Loaf-of-Bread/MassFacebookGroupPoster#3]
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button value="1" class="_42ft _4jy0 _6lth _4jy6 _4jy1 selected _51sy" name="login" data-testid="royal_login_button" type="submit" id="u_0_5_mO">...</button> is not clickable at point (1047, 303). Other element would receive the click: <p>...</p>

**Comment by 1Loaf-of-Bread** [comment]
I am currently working on a large update for this program, this issue will be addressed and fixed in the new update which will use JS to click the buttons directly instead of mimicking a mouse click on the button location. Currently, if a popup or something else was covering the buttons location on the web page it would try to click that instead which would cause this error.

I am working hard on this new update and will try to push it out asap, if you have any more issues please let me know.

Thank you,
Loaf
