### ISSUE TITLE
Error posting on group

### ISSUE THREAD

**Issue by whyrnld** [1Loaf-of-Bread/MassFacebookGroupPoster#4]
When trying to post to our groups, you receive the following error message

There was an error posting to group '128161244057448', the error has been pasted below.
Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF6C47B82B2+55298]
	(No symbol) [0x00007FF6C4725E02]
	(No symbol) [0x00007FF6C45E05AB]
	(No symbol) [0x00007FF6C462175C]
	(No symbol) [0x00007FF6C46218DC]
	(No symbol) [0x00007FF6C465CBC7]
	(No symbol) [0x00007FF6C46420EF]
	(No symbol) [0x00007FF6C465AAA4]
	(No symbol) [0x00007FF6C4641E83]
	(No symbol) [0x00007FF6C461670A]
	(No symbol) [0x00007FF6C4617964]
	GetHandleVerifier [0x00007FF6C4B30AAB+3694587]
	GetHandleVerifier [0x00007FF6C4B8728E+4048862]
	GetHandleVerifier [0x00007FF6C4B7F173+4015811]
	GetHandleVerifier [0x00007FF6C48547D6+695590]
	(No symbol) [0x00007FF6C4730CE8]
	(No symbol) [0x00007FF6C472CF34]
	(No symbol) [0x00007FF6C472D062]
	(No symbol) [0x00007FF6C471D3A3]
	BaseThreadInitThunk [0x00007FFF008D257D+29]
	RtlUserThreadStart [0x00007FFF0240AA58+40]
	

the message I'm trying to post is:
Empresa: #Provale
Cargo: Auxiliar de Produção
Candidate-se: https://maisvagases.com.br/?p=44071

**Comment by 1Loaf-of-Bread** [comment]
Hey, sorry about the delayed response here, I just got back today.

Firstly here are a couple of possible fixes that may solve the issue:

1. Run the command: `pip install --upgrade selenium && pip install --upgrade chromedriver-autoinstaller`. This command will update your versions of the selenium and chromedriver-autoinstaller libraries which could be one of the reasons this bug is occurring.
2. Ensure that the group URL you're posting too is pasted in the group txt file properly, and that the group still exists or you're not blocked/restricted from the group.

Please let me know if this fixes things or if nothing changes. If there is still a bug I would appreciate if you uploaded the whole "Error Logs.txt" file with your next comment.

If neither of those work I will investigate into this issue further, as I think it could something to do with the special characters being used with improper encoding, or an issue with how the text is being pasted.

Thank you,
Loaf
